# =========================================================================
# REACT (VITE) STATIC APP — devShell + Nix-built nginx image
# =========================================================================
# Generated by:  nix flake init -t ~/.omni-nix#react
#
# Defines:
#   1. devShells.default — nodejs + pnpm, direnv-loaded.
#   2. packages.image    — an OCI image: nginx serving the built static app.
#
# ⚠️ ONE-TIME STEP (inherent to reproducible JS builds in Nix): the image is
# built by `buildNpmPackage`, which needs `npmDepsHash` matching app/package-
# lock.json. This template ships `lib.fakeHash` as a PLACEHOLDER — replace it:
#   1. enter the shell:       direnv allow   (or `nix develop`)
#   2. generate the lockfile: (cd app && npm install)
#   3. build the image:       nix build .#image
#        → it FAILS, printing the correct hash. Paste it into `npmDepsHash`
#          below, then re-run `nix build .#image`. (Repeat whenever deps change;
#          `nix run nixpkgs#prefetch-npm-deps -- app/package-lock.json` also works.)
#
# Dev → deploy loop (after the hash is set):
#     just build && just push && just deploy
# =========================================================================
{
  description = "React (Vite) app — Nix devShell + nginx image, just → k3s";

  inputs.nixpkgs.url = "nixpkgs/nixos-26.05";

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
      pkgsFor = system: nixpkgs.legacyPackages.${system};

      imageName = "localhost:5000/react-app";   # keep in lockstep with justfile + manifests
      imageTag  = "latest";
    in {
      packages = forAllSystems (system:
        let
          pkgs = pkgsFor system;
          lib  = nixpkgs.lib;

          # ── build the static app (reproducible, OFFLINE via npmDepsHash) ──
          # buildNpmPackage runs `npm ci` (offline, deps resolved from the
          # hash) then `npm run build` → dist/. installPhase exposes dist/.
          reactBuild = pkgs.buildNpmPackage {
            pname = "react-app";
            version = "0.1.0";
            src = ./app;
            npmDepsHash = lib.fakeHash;     # ← see ⚠️ STEP above; replace on first build
            dontNpmBuild = false;            # run `npm run build` (the default)
            installPhase = ''
              runHook preInstall
              mkdir -p $out
              cp -r dist/* $out/
              runHook postInstall
            '';
          };

          # ── nginx config (same writable-path + docroot pattern as #hugo) ──
          nginxConf = pkgs.writeText "nginx.conf" ''
            worker_processes 1;
            error_log /dev/stderr warn;
            pid        /tmp/nginx.pid;
            events { worker_connections 1024; }
            http {
              access_log /dev/stdout;
              client_body_temp_path /tmp/client_temp;
              proxy_temp_path       /tmp/proxy_temp;
              fastcgi_temp_path     /tmp/fastcgi_temp;
              uwsgi_temp_path       /tmp/uwsgi_temp;
              scgi_temp_path        /tmp/scgi_temp;
              include ${pkgs.nginx}/conf/mime.types;
              default_type application/octet-stream;
              server {
                listen 80;
                root  ${reactBuild};
                index index.html;
                # SPA fallback: serve index.html for client-side routes.
                location / { try_files $uri $uri/ /index.html; }
              }
            }
          '';
        in {
          default = self.packages.${system}.image;
          image = pkgs.dockerTools.buildImage {
            name = imageName;
            tag  = imageTag;
            copyToRoot = [
              pkgs.nginx
              reactBuild
              (pkgs.writeTextDir "etc/passwd" "root:x:0:0::/root:/bin/sh")
              (pkgs.writeTextDir "etc/group"  "root:x:0:")
            ];
            config = {
              Cmd          = [ "${pkgs.nginx}/bin/nginx" "-c" nginxConf ];
              ExposedPorts = { "80/tcp" = { }; };
            };
          };
        });

      devShells = forAllSystems (system:
        let pkgs = pkgsFor system; in {
          default = pkgs.mkShell {
            packages = with pkgs; [
              nodejs_22
              pnpm
              just skopeo kubectl
            ];
            shellHook = ''
              echo ""
              echo "  ❯ react devshell active"
              echo "      node    $(node -v 2>/dev/null || echo '—')"
              echo "      image   ${imageName}:${imageTag}"
              echo "      serve   pnpm dev   (→ http://localhost:5173)"
              echo "      deploy  just build && just push && just deploy"
              echo "      ⚠️ first build needs npmDepsHash — see flake.nix"
              echo ""
            '';
          };
        });
    };
}
