# =========================================================================
# HUGO STATIC SITE — devShell + Nix-built nginx image
# =========================================================================
# Generated by:  nix flake init -t ~/.omni-nix#hugo
#
# Defines:
#   1. devShells.default — hugo + node (asset pipeline), direnv-loaded.
#   2. packages.image    — an OCI image: nginx serving the built static site.
#
# Hugo builds OFFLINE (no network), so the image builds fully reproducibly with
# NO lock/hash step (unlike #react's npm deps).
#
# Dev → deploy loop:
#     just build && just push && just deploy
# =========================================================================
{
  description = "Hugo static site — Nix devShell + nginx image, just → k3s";

  inputs.nixpkgs.url = "nixpkgs/nixos-26.05";

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
      pkgsFor = system: nixpkgs.legacyPackages.${system};

      imageName = "localhost:5000/hugo-site";   # keep in lockstep with justfile + manifests
      imageTag  = "latest";
    in {
      packages = forAllSystems (system:
        let
          pkgs = pkgsFor system;

          # ── build the static site (offline, reproducible) ────────────────
          # nixpkgs ships Hugo's EXTENDED build (SCSS / asset pipeline).
          staticAssets = pkgs.runCommand "hugo-site" {
            nativeBuildInputs = [ pkgs.hugo ];
          } ''
            mkdir -p $out build
            cp -r ${./site}/. build/     # store path is read-only → copy first
            chmod -R u+w build           # hugo may need to write lock/resources
            hugo -s "$PWD/build" --minify --destination "$out"
          '';

          # ── nginx config ─────────────────────────────────────────────────
          # A from-scratch image has no writable /tmp, no /etc/passwd, and
          # nginx's default config points pid/logs/temp at read-only store
          # paths. Override ALL of them or nginx dies at startup. The docroot
          # is the store path of the built site.
          nginxConf = pkgs.writeText "nginx.conf" ''
            worker_processes 1;
            error_log /dev/stderr warn;
            pid        /tmp/nginx.pid;
            events { worker_connections 1024; }
            http {
              access_log /dev/stdout;
              client_body_temp_path /tmp/client_temp;
              proxy_temp_path       /tmp/proxy_temp;
              fastcgi_temp_path     /tmp/fastcgi_temp;
              uwsgi_temp_path       /tmp/uwsgi_temp;
              scgi_temp_path        /tmp/scgi_temp;
              include ${pkgs.nginx}/conf/mime.types;
              default_type application/octet-stream;
              server {
                listen 80;
                root  ${staticAssets};
                index index.html;
                location / { try_files $uri $uri/ =404; }
              }
            }
          '';
        in {
          default = self.packages.${system}.image;
          image = pkgs.dockerTools.buildImage {
            name = imageName;
            tag  = imageTag;
            copyToRoot = [
              pkgs.nginx
              staticAssets
              (pkgs.writeTextDir "etc/passwd" "root:x:0:0::/root:/bin/sh")
              (pkgs.writeTextDir "etc/group"  "root:x:0:")
            ];
            config = {
              Cmd          = [ "${pkgs.nginx}/bin/nginx" "-c" nginxConf ];
              ExposedPorts = { "80/tcp" = { }; };
            };
          };
        });

      devShells = forAllSystems (system:
        let pkgs = pkgsFor system; in {
          default = pkgs.mkShell {
            packages = with pkgs; [
              hugo         # extended build (SCSS / asset pipeline)
              nodejs_22    # Tailwind / PostCSS pipeline if used (npm install once)
              just skopeo kubectl
            ];
            shellHook = ''
              echo ""
              echo "  ❯ hugo devshell active"
              echo "      hugo    $(hugo version 2>/dev/null | awk '{print $2}' | tr -d '+-' || echo '—')"
              echo "      image   ${imageName}:${imageTag}"
              echo "      serve   hugo server -D   (→ http://localhost:1313)"
              echo "      deploy  just build && just push && just deploy"
              echo ""
            '';
          };
        });
    };
}
