# =========================================================================
# HUGO STATIC SITE — devShell + Nix-built nginx image
# =========================================================================
# Generated by:  nix flake init -t ~/.omni-nix#hugo
#
# Defines:
#   1. devShells.default — hugo + node (asset pipeline), direnv-loaded.
#   2. packages.image    — an OCI image: nginx serving the built static site.
#
# Hugo builds OFFLINE (no network), so the image builds fully reproducibly with
# NO lock/hash step (unlike #react's npm deps).
#
# Dev → deploy loop:
#     just build && just push && just deploy
# =========================================================================
{
  description = "Hugo static site — Nix devShell + nginx image, just → k3s";

  inputs.nixpkgs.url = "nixpkgs/nixos-26.05";

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
      pkgsFor = system: nixpkgs.legacyPackages.${system};

      imageName = "localhost:5000/hugo-site";   # keep in lockstep with justfile + manifests
      imageTag  = "latest";
    in {
      packages = forAllSystems (system:
        let
          pkgs = pkgsFor system;

          # ── build the static site (offline, reproducible) ────────────────
          # nixpkgs ships Hugo's EXTENDED build (SCSS / asset pipeline).
          staticAssets = pkgs.runCommand "hugo-site" {
            nativeBuildInputs = [ pkgs.hugo ];
          } ''
            mkdir -p $out build
            cp -r ${./site}/. build/     # store path is read-only → copy first
            chmod -R u+w build           # hugo may need to write lock/resources
            hugo -s "$PWD/build" --minify --destination "$out"
          '';

          # ── nginx config ─────────────────────────────────────────────────
          # A from-scratch image has no writable /tmp, no /etc/passwd, and
          # nginx's default config points pid/logs/temp at read-only store
          # paths. Override ALL of them or nginx dies at startup. The docroot
          # is the store path of the built site.
          nginxConf = pkgs.writeText "nginx.conf" ''
            daemon off;                # run in foreground (PID 1) — default daemon mode forks
                                        # to background, the entry process exits 0, and the
                                        # container stops → "Completed" restart loop.
            # No `user` directive: the container runs as UID 1000 (config.User
            # below). nginx can't switch users when non-root, so it keeps the
            # container uid — no getpwnam("nobody") issue (that only bit as root).
            worker_processes 1;
            error_log /dev/stderr warn;
            pid        /tmp/nginx.pid;
            events { worker_connections 1024; }
            http {
              access_log /dev/stdout;
              client_body_temp_path /tmp/client_temp;
              proxy_temp_path       /tmp/proxy_temp;
              fastcgi_temp_path     /tmp/fastcgi_temp;
              uwsgi_temp_path       /tmp/uwsgi_temp;
              scgi_temp_path        /tmp/scgi_temp;
              include ${pkgs.nginx}/conf/mime.types;
              default_type application/octet-stream;
              server {
                listen 8080;          # non-root can't bind <1024; 8080 is the safe high port
                root  ${staticAssets};
                index index.html;
                location / { try_files $uri $uri/ =404; }
              }
            }
          '';

          # ── writable runtime dirs ──────────────────────────────────────
          # A from-scratch image has no /tmp or /var/log/nginx. nginx writes
          # its pid + client/proxy/... temp files under /tmp, and opens
          # /var/log/nginx/error.log before parsing config — both must exist
          # or nginx dies at startup (mkdir() "/tmp/client_temp" failed).
          runtimeDirs = pkgs.runCommand "nginx-runtime-dirs" { } ''
            mkdir -p $out/tmp $out/var/log/nginx $out/var/cache/nginx
            chmod 1777 $out/tmp
          '';

          # Non-root user (UID 1000) baked in so the manifest can set
          # runAsNonRoot + runAsUser=1000. nginx runs as this uid (no `user`
          # directive in nginx.conf above).
          nonRootUser = pkgs.runCommand "non-root-user" { } ''
            mkdir -p $out/etc
            printf 'root:x:0:0::/root:/bin/sh\nappuser:x:1000:1000::/nonexistent:/bin/sh\n' > $out/etc/passwd
            printf 'root:x:0:\nappuser:x:1000:\n'                                       > $out/etc/group
          '';
        in {
          default = self.packages.${system}.image;
          image = pkgs.dockerTools.buildImage {
            name = imageName;
            tag  = imageTag;
            copyToRoot = [
              pkgs.nginx
              staticAssets
              runtimeDirs
              nonRootUser
            ];
            # nginx's writable dirs (/tmp pid+temp, /var/log/nginx, /var/cache/nginx)
            # are provided by mounts at runtime: emptyDir + fsGroup in the k3s
            # manifest (deploy), `--tmpfs /tmp` in `just test` (smoke). The image
            # itself stays read-only-friendly; -e /dev/stderr below keeps the
            # pre-config error log off /var/log/nginx entirely.
            config = {
              User         = "1000:1000";
              # -e /dev/stderr: send the pre-config error log to stderr so nginx
              # never tries to open /var/log/nginx/error.log before reading config.
              Cmd          = [ "${pkgs.nginx}/bin/nginx" "-c" nginxConf "-e" "/dev/stderr" ];
              ExposedPorts = { "8080/tcp" = { }; };
            };
          };
        });

      devShells = forAllSystems (system:
        let pkgs = pkgsFor system; in {
          default = pkgs.mkShell {
            packages = with pkgs; [
              hugo         # extended build (SCSS / asset pipeline)
              nodejs_22    # Tailwind / PostCSS pipeline if used (npm install once)
              just skopeo kubectl
            ];
            shellHook = ''
              echo ""
              echo "  ❯ hugo devshell active"
              echo "      hugo    $(hugo version 2>/dev/null | awk '{print $2}' | tr -d '+-' || echo '—')"
              echo "      image   ${imageName}:${imageTag}"
              echo "      serve   hugo server -D   (→ http://localhost:1313)"
              echo "      deploy  just build && just push && just deploy"
              echo ""
            '';
          };
        });
    };
}
