# =========================================================================
# PYTHON SERVICE — devShell + reproducible Nix-built container image
# =========================================================================
# Generated by:  nix flake init -t ~/.omni-nix#python
#
# Defines TWO things:
#   1. devShells.default — dev tools, auto-loaded by direnv on `cd`.
#   2. packages.image    — an OCI image built by Nix (NO Dockerfile).
#
# Dev → deploy loop (from this dir, with omni-nix's k3s + registry up):
#     just build     # nix build .#image  →  ./result (image tarball)
#     just push      # skopeo → localhost:5000/pyapp:latest  (no docker)
#     just deploy    # kubectl apply manifests + rollout restart
# =========================================================================
{
  description = "Python web service — Nix devShell + image, just → k3s";

  inputs.nixpkgs.url = "nixpkgs/nixos-26.05";   # flake.lock freezes the exact rev

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
      pkgsFor = system: nixpkgs.legacyPackages.${system};

      # ── project knobs ───────────────────────────────────────────────────
      # Keep image/tag in lockstep with ./justfile and ./manifests/*.yaml.
      imageName = "localhost:5000/pyapp";
      imageTag  = "latest";
    in {
      # =====================================================================
      # 1. CONTAINER IMAGE — built by Nix, reproducible from flake.lock
      # =====================================================================
      # No Dockerfile. `python3.withPackages` wraps the interpreter + runtime
      # deps so gunicorn (and its `flask` import) resolve in-image.
      #
      # Two entries MUST be in copyToRoot or the image breaks at runtime:
      #   • appPython — the gunicorn binary + flask/gunicorn closure. Cmd-string
      #                 refs are NOT auto-scanned into the image closure.
      #   • appSource — the app code, baked at /app.
      # WorkingDir=/app is REQUIRED so gunicorn can import module `app`.
      #
      # Graduation path: for many/PyPI-only deps, swap withPackages for
      # buildPythonApplication + uv2nix (driven by a committed uv.lock) so one
      # source of truth feeds BOTH the image and local dev.
      packages = forAllSystems (system:
        let
          pkgs = pkgsFor system;
          appPython = pkgs.python3.withPackages (p: [ p.flask p.gunicorn ]);
          # Bake app/ into /app/app.py. A bare path in copyToRoot FLATTENS its
          # contents to the image root (→ /app.py, not /app/app.py), so wrap it
          # in a runCommand that emits an `app/` subdir. Then WorkingDir=/app
          # makes gunicorn resolve module `app` at /app/app.py.
          appSource = pkgs.runCommand "app-src" { } ''
            mkdir -p $out/app
            cp -r ${./app}/. $out/app/
          '';
        in {
          default = self.packages.${system}.image;
          image = pkgs.dockerTools.buildImage {
            name = imageName;
            tag  = imageTag;
            copyToRoot = [ appPython appSource ];
            config = {
              WorkingDir   = "/app";
              Cmd          = [ "${appPython}/bin/gunicorn" "app:app" "--bind" "0.0.0.0:8080" ];
              ExposedPorts = { "8080/tcp" = {}; };
            };
          };
        });

      # =====================================================================
      # 2. DEV SHELL — auto-loaded by direnv (./.envrc → `use flake`)
      # =====================================================================
      devShells = forAllSystems (system:
        let pkgs = pkgsFor system; in {
          default = pkgs.mkShell {
            packages = with pkgs; [
              # ── Python ───────────────────────────────────────────────────
              python3      # interpreter (deps come from uv → .venv, NOT system pip)
              uv           # venv + dependency manager (avoids PEP-668)
              ruff         # lint + format
              mypy         # type-check

              # ── Pipeline ─────────────────────────────────────────────────
              # Also global on omni-nix (dev-tools.nix); listed here so a
              # scaffolded project is self-sufficient on any host.
              just
              skopeo
              kubectl
            ];

            shellHook = ''
              echo ""
              echo "  ❯ python devshell active"
              echo "      python  $(python3 --version 2>&1 | awk '{print $2}')"
              echo "      image   ${imageName}:${imageTag}"
              echo "      deploy  just build && just push && just deploy"
              echo ""
            '';
          };
        });
    };
}
