# =========================================================================
# PYTHON — FastAPI web service  OR  plain runnable script
# =========================================================================
# Generated by:  nix flake init -t ~/.omni-nix#python
#
# Pick your VARIANT (one line below) — everything follows it: the image
# entrypoint + the manifest dir + the justfile recipes.
#   variant = "fastapi"  → HTTP service (uvicorn main:app), Deployment + Service
#   variant = "script"   → plain script (python script.py), Kubernetes Job
#
# DEPS: pyproject.toml + uv.lock are the SINGLE source of truth for both the
# dev shell and the image (via uv2nix). No more requirements.txt-vs-withPackages
# drift. Edit pyproject.toml → `uv lock` → `just build`.
#
# Dev → deploy loop (from this dir, with omni-nix's k3s + registry up):
#     just build && just push && just deploy
# Full guide: README.md
# =========================================================================
{
  description = "Python — FastAPI service or plain script (Nix image → k3s)";

  inputs = {
    nixpkgs.url = "nixpkgs/nixos-26.05";   # flake.lock freezes the exact rev

    # uv2nix: build a Python venv from uv.lock — the single source of truth for
    # both the dev shell and the image. pyproject-build-systems supplies the
    # PEP-517 build backends uv2nix needs when building sdists.
    pyproject-nix.url = "github:pyproject-nix/pyproject.nix";
    pyproject-nix.inputs.nixpkgs.follows = "nixpkgs";
    uv2nix.url = "github:pyproject-nix/uv2nix";
    uv2nix.inputs.pyproject-nix.follows = "pyproject-nix";
    uv2nix.inputs.nixpkgs.follows = "nixpkgs";
    pyproject-build-systems = {
      url = "github:pyproject-nix/build-system-pkgs";
      inputs.pyproject-nix.follows = "pyproject-nix";
      inputs.uv2nix.follows = "uv2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, uv2nix, pyproject-nix, pyproject-build-systems }:
    let
      systems = [ "x86_64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;

      # ── VARIANT ─────────────────────────────────────────────────────────
      # "fastapi" = web service | "script" = plain runnable script.
      # Keep in sync with the `variant` line in ./justfile.
      variant = "fastapi";
      isWeb   = variant == "fastapi";

      # keep in lockstep with ./justfile (image/tag/dep) + manifests/<variant>/
      imageName = "localhost:5000/pyapp";
      imageTag  = "latest";

      # Per-system: pkgs + the uv2nix venv (shared by the image + devShell, so
      # both always derive from the same uv.lock).
      perSystem = system:
        let
          pkgs = nixpkgs.legacyPackages.${system};
          lib  = nixpkgs.lib;

          # Load pyproject.toml + uv.lock as a uv workspace; build an overlay
          # that supplies every dependency from the lock (wheels preferred).
          workspace = uv2nix.lib.workspace.loadWorkspace { workspaceRoot = ./.; };
          overlay   = workspace.mkPyprojectOverlay { sourcePreference = "wheel"; };

          # Base Python package set (pyproject.nix) + the uv2nix lock overlay +
          # the PEP-517 build-backend set (so sdist builds resolve their backend).
          pythonSet = (pkgs.callPackage pyproject-nix.build.packages {
            python = pkgs.python3;
          }).overrideScope (lib.composeManyExtensions [
            pyproject-build-systems.overlays.default
            overlay
          ]);

          # The venv — ONE source of truth for both the image and the devShell.
          venv = pythonSet.mkVirtualEnv "pyapp-env" workspace.deps.default;
        in { inherit pkgs venv; };
    in {
      # =====================================================================
      # 1. CONTAINER IMAGE — built by Nix, reproducible from flake.lock
      # =====================================================================
      # No Dockerfile. copyToRoot = [ venv appSource nonRootUser ] (Cmd-string
      # refs are NOT auto-scanned into the closure). WorkingDir=/app so uvicorn
      # resolves module `main` at /app/main.py.
      packages = forAllSystems (system:
        let
          ps   = perSystem system;
          pkgs = ps.pkgs;
          venv = ps.venv;

          # entrypoint per variant — uses the venv's binaries (uvicorn / python)
          cmd =
            if isWeb
            then [ "${venv}/bin/uvicorn" "main:app" "--host" "0.0.0.0" "--port" "8080" ]
            else [ "${venv}/bin/python" "/app/script.py" ];

          # Bake app/ into /app (a bare path in copyToRoot flattens its contents
          # to the image root → /main.py, not /app/main.py), so wrap it in a
          # runCommand that emits an `app/` subdir.
          appSource = pkgs.runCommand "app-src" { } ''
            mkdir -p $out/app
            cp -r ${./app}/. $out/app/
          '';

          # Non-root user (UID 1000) baked in so the manifest can set
          # runAsNonRoot + runAsUser=1000. Provides /etc/passwd + /etc/group
          # (root + appuser); config.User runs the entrypoint as 1000:1000.
          nonRootUser = pkgs.runCommand "non-root-user" { } ''
            mkdir -p $out/etc
            printf 'root:x:0:0::/root:/bin/sh\nappuser:x:1000:1000::/app:/bin/sh\n' > $out/etc/passwd
            printf 'root:x:0:\nappuser:x:1000:\n'                                 > $out/etc/group
          '';
        in {
          default = self.packages.${system}.image;
          image = pkgs.dockerTools.buildImage {
            name = imageName;
            tag  = imageTag;
            copyToRoot = [ venv appSource nonRootUser ];
            config = {
              User       = "1000:1000";   # non-root (see nonRootUser above)
              WorkingDir = "/app";
              Cmd        = cmd;
            } // (if isWeb then { ExposedPorts = { "8080/tcp" = { }; }; } else { });
          };
        });

      # =====================================================================
      # 2. DEV SHELL — auto-loaded by direnv (./.envrc → `use flake`)
      # =====================================================================
      devShells = forAllSystems (system:
        let
          ps   = perSystem system;
          pkgs = ps.pkgs;
          venv = ps.venv;
        in {
          default = pkgs.mkShell {
            packages = [
              venv            # deps from uv.lock — SAME source as the image
              pkgs.uv         # `uv lock` / `uv sync` to refresh deps
              pkgs.ruff pkgs.mypy
              pkgs.just pkgs.skopeo pkgs.kubectl
            ];
            shellHook = ''
              echo ""
              echo "  ❯ python devshell active  [variant: ${variant}]"
              echo "      venv   $(readlink -f ${venv})"
              echo "      image  ${imageName}:${imageTag}"
              echo "      deps   edit pyproject.toml → \`uv lock\` → rebuild"
              echo "      run    just run    · deploy  just deploy"
              echo ""
              # Undo nixpkgs PYTHONPATH propagation so the venv's site-packages win.
              unset PYTHONPATH
            '';
          };
        });
    };
}
