# =========================================================================
# PYTHON — FastAPI web service  OR  plain runnable script
# =========================================================================
# Generated by:  nix flake init -t ~/.omni-nix#python
#
# Pick your VARIANT (one line below) — everything follows it: the image
# entrypoint + deps, the manifest dir, and the justfile recipes.
#   variant = "fastapi"  → HTTP service (uvicorn main:app), Deployment + Service
#   variant = "script"   → plain script (python script.py), Kubernetes Job
#
# Dev → deploy loop (from this dir, with omni-nix's k3s + registry up):
#     just build && just push && just deploy
# Full guide: README.md
# =========================================================================
{
  description = "Python — FastAPI service or plain script (Nix image → k3s)";

  inputs.nixpkgs.url = "nixpkgs/nixos-26.05";   # flake.lock freezes the exact rev

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
      pkgsFor = system: nixpkgs.legacyPackages.${system};

      # ── VARIANT ─────────────────────────────────────────────────────────
      # "fastapi" = web service | "script" = plain runnable script.
      # Keep this in sync with the `variant` line in ./justfile.
      variant = "fastapi";
      isWeb   = variant == "fastapi";

      # keep in lockstep with ./justfile (image/tag/dep) + manifests/<variant>/
      imageName = "localhost:5000/pyapp";
      imageTag  = "latest";
    in {
      # =====================================================================
      # 1. CONTAINER IMAGE — built by Nix, reproducible from flake.lock
      # =====================================================================
      # No Dockerfile. The entrypoint + runtime deps branch on `variant`:
      #   • fastapi → uvicorn serving app/main.py on :8080
      #   • script  → `python /app/script.py` (run to completion → K8s Job)
      # Both `appPython` and `appSource` MUST be in copyToRoot (Cmd-string refs
      # are NOT auto-scanned into the image closure). WorkingDir=/app so uvicorn
      # resolves module `main` at /app/main.py.
      packages = forAllSystems (system:
        let
          pkgs = pkgsFor system;

          # runtime interpreter + deps (the IMAGE's source of truth)
          appPython =
            if isWeb
            then pkgs.python3.withPackages (p: [ p.fastapi p.uvicorn ])
            else pkgs.python3.withPackages (p: [ ]);   # plain script — add deps here

          # entrypoint per variant
          cmd =
            if isWeb
            then [ "${appPython}/bin/uvicorn" "main:app" "--host" "0.0.0.0" "--port" "8080" ]
            else [ "${appPython}/bin/python" "/app/script.py" ];

          # Bake app/ into /app. A bare path in copyToRoot FLATTENS its contents
          # to the image root (→ /main.py, not /app/main.py), so wrap it in a
          # runCommand that emits an `app/` subdir.
          appSource = pkgs.runCommand "app-src" { } ''
            mkdir -p $out/app
            cp -r ${./app}/. $out/app/
          '';
        in {
          default = self.packages.${system}.image;
          image = pkgs.dockerTools.buildImage {
            name = imageName;
            tag  = imageTag;
            copyToRoot = [ appPython appSource ];
            config = {
              WorkingDir = "/app";
              Cmd        = cmd;
            } // (if isWeb then { ExposedPorts = { "8080/tcp" = { }; }; } else { });
          };
        });

      # =====================================================================
      # 2. DEV SHELL — auto-loaded by direnv (./.envrc → `use flake`)
      # =====================================================================
      devShells = forAllSystems (system:
        let pkgs = pkgsFor system; in {
          default = pkgs.mkShell {
            packages = with pkgs; [
              # ── Python ───────────────────────────────────────────────────
              python3      # interpreter (deps come from uv → .venv, NOT system pip)
              uv           # venv + dependency manager (avoids PEP-668)
              ruff mypy    # lint + type-check

              # ── Pipeline ─────────────────────────────────────────────────
              # Also global on omni-nix (dev-tools.nix); listed here so a
              # scaffolded project is self-sufficient on any host.
              just skopeo kubectl
            ];

            shellHook = ''
              echo ""
              echo "  ❯ python devshell active  [variant: ${variant}]"
              echo "      python  $(python3 --version 2>&1 | awk '{print $2}')"
              echo "      image   ${imageName}:${imageTag}"
              echo "      run     just run    · deploy  just deploy"
              echo ""
            '';
          };
        });
    };
}
