# =========================================================================
# PROJECT DEVELOPMENT SHELL
# =========================================================================
# Generated by:  nix flake init -t ~/.omni-nix#dev
#
# This flake defines ONE thing: a `devShell` — the tools this project needs.
# It is loaded automatically by direnv (see ./.envrc → `use flake`) when you
# `cd` into the project, and unloaded when you leave. Nothing here is global.
#
# Edit freely: delete the lines/packages this project does not need, and
# re-run `direnv allow` (or just touch .envrc) to reload. nix-direnv caches
# the evaluation, so subsequent cd's are instant.
#
# Find packages:  https://search.nixos.org/packages
# =========================================================================
{
  description = "Project development shell (node / python / hugo / tailwind)";

  inputs.nixpkgs.url = "nixpkgs/nixos-26.05";   # pin a channel; flake.lock freezes the exact rev

  outputs = { self, nixpkgs }:
    let
      # ── Systems this project is expected to build on ────────────────────
      systems = [ "x86_64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
      pkgsFor = system: nixpkgs.legacyPackages.${system};
    in {
      devShells = forAllSystems (system:
        let pkgs = pkgsFor system; in {
          default = pkgs.mkShell {
            # ───────────────────────────────────────────────────────────────
            # TOOLCHAIN — list ONLY what this project needs.
            # ───────────────────────────────────────────────────────────────
            packages = with pkgs; [
              # ── JavaScript / React ───────────────────────────────────────
              nodejs_22        # LTS; bump to nodejs_24 or nodejs_latest as needed
              pnpm             # JS package manager — swap for `yarn`, or drop to use bundled `npm`

              # ── Tailwind (standalone CLI) ────────────────────────────────
              # Only needed if you run `tailwindcss` directly. For React apps
              # Tailwind usually comes via npm — delete this line in that case.
              tailwindcss

              # ── Static site generator ────────────────────────────────────
              hugo

              # ── Python ───────────────────────────────────────────────────
              # The interpreter comes from Nix; deps/venvs are managed by `uv`
              # (NOT system pip — Nix's Python is read-only, pip would hit
              # PEP-668). First time in the shell:
              #     uv venv && source .venv/bin/activate
              #     uv pip install -r requirements.txt   # (or uv sync)
              python3
              uv
            ];

            # ── Welcome banner — runs once per shell load ──────────────────
            # Shown by direnv on the first cd (cached after).
            shellHook = ''
              echo ""
              echo "  ❯ devshell active"
              echo "      node    $(node -v 2>/dev/null || echo '—')"
              echo "      python  $(python3 --version 2>&1 | awk '{print $2}')"
              echo "      hugo    $(hugo version 2>/dev/null | awk '{print $2}' | tr -d '+-' || echo '—')"
              echo ""
            '';
          };
        });
    };
}
